### ISSUE TITLE
New entity from v5.4.2 not in DWD

### ISSUE THREAD

**Issue by aphedges** [e-spaulding/xpo#22]
The qnode [Q113688270](https://www.wikidata.org/wiki/Q113688270) (`test facility`), which was introduced in v5.4.2, is not in DWD. The qnode was created more recently than the Wikidata dump used to create DWD.

As a side note, I noticed that 62740869c1abdb205289b1463d5ca44d858a52e7 deleted entries for the qnodes I said were "not present in DWD" in #20. However, that was not needed for all of them. For example, `Q17285919` (from v5.4) was renamed to `Q12348865`, and the new identifier _is_ in DWD. I don't have a particularly strong need for the entries you removed, but I figured I should let you know.

**Comment by e-spaulding** [comment]
I mentioned this to Martha and some annotators and I was instructed to add the non-DWD nodes back in for the sake of fuller coverage, and because performers are not restricted to DWD. So, the next release will have them added back in, but we are having a meeting tomorrow at noon Mountain time if you would like to attend and discuss this choice.

**Comment by aphedges** [comment]
@e-spaulding, understood. I believe we filter out any qnodes not in DWD, so it shouldn't break anything. We just can't use them.

I would just appreciate if you could use versions of the qnode present in DWD, if one exists.
